### ISSUE TITLE
Allow Running the script with root priviledge

### ISSUE THREAD

**Issue by imtiazShakil** [Kron4ek/wine-portable-executable#4]
Hello,

I'm using kali linux which comes with a single root user. Whenever I try to run `wine-portable-5.2-staging-amd64.sh` I get this message:

> Do not run this app as root!

Can you change this behaviour?

**Comment by Kron4ek** [comment]
Hello. I've added such ability and reuploaded the 5.2 build. You can now run it as root like this:

    ALLOW_ROOT=1 ./wine-portable-5.2-staging-amd64.sh
