### ISSUE TITLE
project is difficult to install

### ISSUE THREAD

**Issue by blingu** [Kron4ek/wine-portable-executable#6]
Hi,
I've been trying to get this to work for some time now. I installed all required libraries, cloned the project and ran create_wine_portable.sh. This made a wine-portable.sh, which gives me the following input once I run it:
Wine (amd64) Portable SquashFS

tar: Error opening archive: Unrecognized archive format
chmod: cannot access '/tmp/wine-portable.sh_nrb_29965/squashfuse/squashfuse-amd64/squashfuse': No such file or directory
./wine-portable.sh: line 98: /tmp/wine-portable.sh_nrb_29965/squashfuse/squashfuse-amd64/squashfuse: No such file or directory
Mounting the squashfs image failed!

I also downloaded the ready-to-go binary called wine-portable-5.15-staging-amd64.sh. Running it gives me the following issue:
Wine-Staging 5.15 (amd64) Portable SquashFS

/tmp/wine-portable-5.15-staging-amd64.sh_nrb_27179/mnt/wine.sh: line 22: /tmp/wine-portable-5.15-staging-amd64.sh_nrb_27179/mnt/wine/bin/wine: No such file or directoryWine-Staging 5.15 (amd64) Portable SquashFS

/tmp/wine-portable-5.15-staging-amd64.sh_nrb_27179/mnt/wine.sh: line 22: /tmp/wine-portable-5.15-staging-amd64.sh_nrb_27179/mnt/wine/bin/wine: No such file or directory

Could you please explain more how to install it? I'd appreciate it.

**Comment by blingu** [comment]
I'm using Void Linux. I installed 32-bit glibc like you told me, and wine-portable-5.15-staging-amd64.sh partially works now. If I start winecfg, it takes long for it to appear (I have freetype installed). Output:
Wine-Staging 5.15 (amd64) Portable SquashFS

002c:fixme:winediag:__wine_start_process Wine Staging 5.15 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"SecDrv" failed to start: 2
0040:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0040:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0040:err:ole:get_local_server_stream Failed: 80004002
0024:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
004c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)

**Comment by Kron4ek** [comment]
> Wine cannot find the FreeType font library. To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.

32-bit freetype is required to eliminate this error, maybe installing it will also fix the long launch issue.

**Comment by Kron4ek** [comment]
And the first problem (i mean "tar: Error opening archive: Unrecognized archive format") is actually because in Void Linux git doesn't clone LFS object by default. It's necessary to install git-lfs:

    xbps-install git-lfs

And perform this command (without root rights):

    git lfs install

After that clone the repo again.

**Comment by blingu** [comment]
the tar issue got resolved, freetype as well. but then i run into issues like libgcc_s.so.1 is required for pthread_cancel to work and my program doesn't work. seems like installing normal wine is just going to solve the issues faster, but i like the idea of having a sane portable wine install.

**Comment by Kron4ek** [comment]
Unfortunately the integrated runtime isn't perfectly tested and incomplete, so issues may arise. If you install all (or most) Wine dependencies, you can then disable the integrated libraries, which should solve most problems:

    export DISABLE_RUNTIME=1
    ./wine-portable-5.x-staging-amd64.sh application.exe

That doesn't make much sense, but still you can do this in case you want.
