### ISSUE TITLE
Can't find /mnt/wine/bin/wine

### ISSUE THREAD

**Issue by thenoobtester** [Kron4ek/wine-portable-executable#7]
Hi,

great project I love the idea, I just downloaded a release and when I try to run it after making it executable I get :

`/tmp/wine-portable-6.0-rc2-staging-amd64.sh_guest_26262/mnt/wine.sh: line 22: /tmp/wine-portable-6.0-rc2-staging-amd64.sh_guest_26262/mnt/wine/bin/wine: No such file or directory`

Have you seen this before? 

Thank you
OS:Debian 9 Stretch, 64bit.

**Comment by Kron4ek** [comment]
Hi, 

this is because Debian 9 has glibc version older than required (2.27 or newer is needed, but Debian 9 has version 2.24).

**Comment by thenoobtester** [comment]
Thank you for the quick answer. Is it possible to remedy or am I wasting my time.

**Comment by Kron4ek** [comment]
This can be solved in two ways: by updating distribution (to Debian 10, for example) or by recreating runtime and recompiling squashfs-tools and Wine on distro with glibc 2.24 or older.

It is also possible to update libc6 from testing repos, but i don't recommend this as this may affect system stability negatively.

**Comment by thenoobtester** [comment]
OK, thank you for your help and for publishing this project.
