### ISSUE TITLE
Problem  on mounting  Wine-Staging 6.0-rc4 (amd64) Portable

### ISSUE THREAD

**Issue by anwarmax-cpu** [Kron4ek/wine-portable-executable#8]
Wine-Staging 6.0-rc4 (amd64) Portable SquashFS

Can't find the root of this filesystem!
Mounting the squashfs image failed!

**Comment by Kron4ek** [comment]
What Linux distro do you use?

**Comment by anwarmax-cpu** [comment]
Ubuntu 20.4  
mesa 20 driver

**Comment by Kron4ek** [comment]
What about wine-portable-6.0-staging-tkg-amd64.sh from the releases page, does it work for you? It works for me on Ubuntu 20.04.

**Comment by anwarmax-cpu** [comment]
sorry  for the delayed response  but your wine build that are not portable  (not .sh) work  thanks I guess  I will use those

**Comment by anwarmax-cpu** [comment]
you could consider  this issue  solved thanks again
