### ISSUE TITLE
[Question] AppImage?

### ISSUE THREAD

**Issue by probonopd** [Kron4ek/wine-portable-executable#9]
Hello Kron4ek, out of curiosity:

* Are you aware of https://github.com/sudo-give-me-coffee/wine32-deploy and https://github.com/Hackerl/Wine_Appimage?
* What were the reason you decided not to use AppImage but something (very) similar?

**Comment by Kron4ek** [comment]
Hello.

> Are you aware of https://github.com/sudo-give-me-coffee/wine32-deploy and https://github.com/Hackerl/Wine_Appimage?

Yes, i'm aware about the second one, didn't know about the first though.

> What were the reason you decided not to use AppImage but something (very) similar?

Well, there were no particular reasons, i was just curious to create something similar myself.

**Comment by probonopd** [comment]
Thanks for answering @Kron4ek.
